name:                effective-haskell
version:             0.1.0.0
github:              "githubuser/effective-haskell"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/effective-haskell#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-unused-top-binds
- -Wno-type-defaults
library:
  source-dirs: src

executables:
  effective-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - effective-haskell
    - directory
    - containers
  custom-type:
    main:                Main.hs
    source-dirs:         custom-type
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  record-wild-cards:
    main:                Main.hs
    source-dirs:         record-wild-cards
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  sum-types:
    main:                Main.hs
    source-dirs:         sum-types
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  peano:
    main:                Main.hs
    source-dirs:         peano
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  calculator:
    main:                Main.hs
    source-dirs:         calculator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  function:
    main: Main.hs
    source-dirs: function-as-values
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  exercise4:
    main: Main.hs
    source-dirs: chapter4-exercise
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  exercise2:
    main: Main.hs
    source-dirs: chapter2-exercise
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  chapter3:
    main: Main.hs
    source-dirs: chapter3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  chapter6:
    main: Main.hs
    source-dirs: chapter6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  exercise6:
    main: Main.hs
    source-dirs: chapter6-exercise
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
tests:
  effective-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - effective-haskell
